betagouv/acces-cible

app/controllers/sites_controller.rb
app/models/audit.rb
app/models/site.rb
config/locales/fr.yml
spec/models/audit_spec.rb
spec/models/site_spec.rb

- Rename "page" to "déclaration"
- Rename "audit" to "vérification"
- List sites by most recent audit.checked_at

feat: Update interface to improve usability

---

.rubocop.yml
app/models/link.rb
app/models/page.rb
spec/models/link_list_spec.rb
spec/models/link_spec.rb
spec/models/page_spec.rb

Relative links pointing to the same location would be considered different, leading to crawling the same page several times.
Now `/a/../b` correctly resolves to `/b`, `//path` to `/path`, etc.

fix: Deduplicate relative links

---

app/controllers/sites_controller.rb
app/jobs/run_audit_job.rb
app/models/audit.rb
app/models/check.rb
app/models/site.rb
spec/models/check_spec.rb

Avoid timeouts when running all checks simultaneously

feat: Audit asynchronously

---

app/helpers/application_helper.rb
app/views/sites/index.html.erb
spec/helpers/application_helper_spec.rb

- `icon` to insert an icon. Tag option defaults to `span` with `aria-hidden: true`.
- `link_icon` to generate links. Accepts `size` and `btn` options (`true/primary/secondary/tertiary`).
- and an `icon_class` base helper, which accepts `size`, `side`, and `fill/line` options.

Feat: Add icon helpers

---

app/libs/string_comparison.rb
app/models/check.rb
app/models/checks/accessibility_page_heading.rb
app/models/page.rb
app/models/page_heading_status.rb
app/views/checks/_accessibility_page_heading.html.erb
config/locales/fr.yml
spec/lib/string_comparison_spec.rb
spec/models/checks/accessibility_page_heading_spec.rb
spec/models/page_spec.rb

This was tricky, as it required allowing some leeway for typos, incorrect order, and even nesting under extra headings, while enforcing a required order.
Introduces a `StringComparison` helper module, in `app/libs`, which provides `similar?` and `similarity_ratio` methods.

feat: Add check for accessibility page heading structure

---

Gemfile
Gemfile.lock
app/jobs/update_audit_job.rb
app/models/audit.rb
app/models/site.rb
db/migrate/20250507132936_add_current_to_audits.rb
db/schema.rb
spec/factories/audits.rb
spec/models/audit_spec.rb
spec/models/site_spec.rb

- Remove has_some_of_many because the generated SQL breaks chaining
- Indicate current audit using a boolean, which simplifies preloading
- Update site.audit to return the current audit, or the latest, or build a new one

refactor: Simplify association between site and current audit

---

app/jobs/run_audit_job.rb
app/models/audit.rb
app/models/link.rb
db/migrate/20250527120328_add_scheduled_to_audits.rb
db/schema.rb

Adding a site or requesting a new audit caused an unnecessary amount of UpdateAuditJob. This should no longer happen, lightening the load on the worker instance.

fix: Prevent duplicate audit jobs

---

README.md
app/export/application_export.rb
app/export/csv_export.rb
app/export/site_csv_export.rb
spec/export/application_export_spec.rb
spec/export/csv_export_spec.rb

refactor: Extract common Export code

---

app/controllers/sites_controller.rb
app/jobs/schedule_audits_job.rb
app/models/site.rb
spec/requests/sites_controller_spec.rb

**Audit Scheduling Logic Removal:**
* Removed the call to `@site.audit.schedule` when creating a new site in `SitesController#create`
* Removed the call to `ScheduleAuditsJob.perform_later` in `SitesController#upload`
**Model Logic Updates:**
* Updated the `Site` model's `after_save` callback to correctly handle cases when `audits_count_before_last_save` is `nil`

fix: duplicate call to audit schedule & set current audit

---

app/models/browser.rb
app/models/check.rb
spec/jobs/process_audit_job_spec.rb
spec/models/browser_spec.rb
spec/models/check_spec.rb

I've retried some non-Ferrum errors which were retryable after all. I've therefore listed retryable errors explicitly, which is more readable anyway.

refactor: Edit retryable errors

---

app/jobs/process_audit_job.rb
app/jobs/run_check_job.rb
app/models/audit.rb
app/models/browser.rb
spec/jobs/process_audit_job_spec.rb
spec/jobs/run_check_job_spec.rb
spec/models/audit_spec.rb
spec/models/browser_spec.rb

À la demande générale de @freesteph, et pour que ce soit plus clair quand on étudie les logs des jobs, cette PR crée un job spécifique pour les checks.

refactor: Split audit and check jobs

---

Gemfile.lock
app/helpers/application_helper.rb
app/queries/site_query.rb
features/page_des_sites.feature
spec/queries/site_query_spec.rb

- Fix params matching in SiteQuery order_by to use string instead of symbol
- Add test coverage for URL sorting
- Add [cucumber step](https://github.com/betagouv/betagouv-cucumber-steps/pull/1) for validating table order
- Fix sort icon accessibility by removing duplicate text parameter

fix: SiteQuery sorting

---

app/helpers/check_helper.rb
app/models/audit.rb
app/models/check_state_machine.rb
config/locales/fr.yml
spec/models/audit_spec.rb

L'état "échoué" est désormais réservé pour les contrôles qui ont échoué, ceux qui n'ont pas pu tourner sont basculés sur l'état "annulé". Corrige un problème de transition interdite.

fix: Add aborted state for checks that could not run

---

bin/cucumber

Pour ne plus avoir besoin de taper `bundle exec bin/cucumber` (les scripts dans `bin/` sont sensés prendre le setup du projet en compte).

chore: Remove bundle warnings when running bin/cucumber

---

app/models/browser.rb
spec/models/browser_spec.rb

- Rename restart! to cleanup! to match actual behaviour
- Always release Ferrum/Chrome after use

feat: Prevent browser leaks

---

docker-compose.yml

- solid_queue and debug gem are not being friendly with each other
- the debug port and the range fixes the issue of the service not starting
https://github.com/rails/solid_queue/issues/572

fix: Add debug port to jobs docker service

---

app/controllers/concerns/authentication.rb
app/jobs/remove_inactive_sessions_job.rb
app/models/session.rb
app/models/user.rb
config/recurring.yml
spec/jobs/remove_inactive_sessions_job_spec.rb
spec/jobs/remove_inactive_users_job_spec.rb
spec/models/user_spec.rb
spec/requests/authentication_spec.rb
spec/support/auth_helpers.rb

refactor: Improve authentication management

---

app/models/checks/accessibility_mention.rb
spec/models/checks/accessibility_mention_spec.rb

Allow parenthesis around level but ban words between "Accessibilité" and level.

fix: Adjust allowed format for accessibility mention

---

bin/scalingo

Just a little tweak to the scalingo CLI helper to allow connecting to a bash console as well as Rails'.

feat: Allow connecting to bash on scalingo

---

app/controllers/sites_controller.rb
app/queries/site_query.rb
app/views/shared/_filter.html.erb
app/views/sites/_site.html.erb
app/views/sites/index.html.erb
config/locales/fr.yml
features/page_des_sites.feature
features/step_definitions/site_steps.rb
spec/queries/site_query_spec.rb

- Update `SiteQuery` to support filtering by tag using `tag_id`
- Add a tag filter dropdown to the site index view
- Load tags in `SitesController` for filtering options

feat: Add tag filtering to site index

---

Gemfile
Gemfile.lock

Chrome includes brotli/zstd decompression, Ferrum only needs to include it in accept-encoding headers.

refactor: Remove unused gems from Gemfile
